# main text of home
name: 'Invest In Yourself'
bio: 'Manifest Life Inc is a nonprofit lifestyle brand helping Millennials self-identify as leaders, providing financial and consulting insights. The brand believes in fostering an ecosystem that is built upon design-thinking and solution-based collaborations.'
# if it's an external image, update below for true
external-image: false
picture: 'assets/images/profile.png'

url: http://www.manifest.life
# your url: http://USERNAME.github.io

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-77539742-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: mydisqus

# if you don't have any of social below, comment the line
facebook: manifestlifeinc
twitter: manifestlifeinc
google: manifestlife
instagram: manifestlifeinc
pinterest: manifestlifeinc
linkedin: manifestlife
youtube: manifestlife
spotify: myspotify
github: manifestlifeinc
medium: manifestlifeinc
email: we@manifest.life

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-coffeescript
  - jekyll-watch
#  - jekyll-assets

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh, .DS_store]
