source 'http://rubygems.org'

gem 'github-pages'
gem 'rake'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'jekyll-coffeescript'
